[tool.poetry]
name = "keiko"
version = "0.0.1.dev1"
description = "KAT report engine using LateX to generate PDF"
authors = ["MinVWS <maintainer@openkat.nl>"]
license = "EUPL"

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.1.3"
pydantic = "^1.9.2"
Jinja2 = "^3.1.2"
fastapi = "^0.88"
uvicorn = "^0.20.0"
vulture = "^2.5"
opentelemetry-sdk = "^1.17.0"
opentelemetry-exporter-otlp-proto-grpc = "1.17.0"
opentelemetry-instrumentation-fastapi = "^0.38b0"
requests = "^2.30.0"
certifi = "^2023.5.7"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
httpx = "^0.24.1"
robotframework-tidy = "^3.2"
robotframework = "^6.0.1"
robotframework-debuglibrary = "^2.3.0"
robotframework-requests = "^0.9.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
