name: Check Poetry dependencies

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        id: py38
        with:
          python-version: 3.8
          cache: pip

      - name: Install pip dependencies
        run: pip install poetry poetry-plugin-export

      - name: Check, lock, and export Poetry dependencies
        run: make poetry-dependencies

      - name: Check if there are any changed files
        run: git diff --exit-code
